positional_arguments:
optional_arguments:
	help : None
 #show this help message and exit
	exclude : []
 #Comma separated Exclude directory path
	version : None
 #show program's version number and exit
	disable-version-check : False
 #skips checking for a new version
	disable-validation-check : False
 #skips checking xml files against schema
	offline : False
 #operate in offline mode
	detailed : False
 #display detailed report
CVE_Data_Download:
	nvd : json
 #choose method for getting CVE lists from NVD
	update : daily
 #update schedule for data sources and exploits database (default: daily)
	nvd-api-key : 
 #specify NVD API key (used to improve NVD rate limit)
	disable-data-source : []
 #comma-separated list of data sources (CURL, GAD, NVD, OSV, REDHAT, RSD) to disable (default: NONE)
	use-mirror : 
 #use an mirror to update the database
Input:
	directory : 
 #
	input-file : 
 #provide input filename
	triage-input-file : 
 #provide input filename for triage data
	config : 
 #provide config file
	package-list : 
 #provide package list
	sbom : spdx
 #specify type of software bill of materials (sbom) (default: spdx)
	sbom-file : 
 #provide sbom filename
Output:
	quiet : False
 #suppress output
	log : info
 #log level (default: info)
	output-file : 
 #provide output filename (default: output to stdout)
	html-theme : 
 #provide custom theme directory for HTML Report
	format : console
 #update output format (default: console)	specify multiple output formats by using comma (',') as a separator	note: don't use spaces between comma (',') and the output formats.	
	generate-config : yaml,toml
 #generate config file for cve bin tool in toml and yaml formats.
	cvss : 0
 #minimum CVSS score (as integer in range 0 to 10) to report (default: 0)
	severity : low
 #minimum CVE severity to report (default: low)
	report : False
 #Produces a report even if there are no CVE for the respective output format
	available-fix : 
 #Lists available fixes of the package from Linux distribution
	backport-fix : 
 #Lists backported fixes if available from Linux distribution
	affected-versions : 0
 #Lists versions of product affected by a given CVE (to facilitate upgrades)
	vex : 
 #Provide vulnerability exchange (vex) filename
Merge_Report:
	append : False
 #save output as intermediate report in json format
	tag : 
 #add a unique tag to differentiate between multiple intermediate reports
	merge : None
 #comma separated intermediate reports path for merging
	filter : []
 #comma separated tag string for filtering intermediate reports
Checkers:
	skips : 
 #comma-separated list of checkers to disable
	runs : 
 #comma-separated list of checkers to enable
Database_Management:
	import-json : 
 #import database from json files chopped by years
	export-json : 
 #export database as json files chopped by years
	export : 
 #export database filename
	import : 
 #import database filename
Exploits:
	exploits : False
 #check for exploits from found cves
Deprecated:
	extract : True
 #autoextract compressed files
