[tool.isort]
profile = "black"

[tool.flake8]
exclude = "build"
max_line_length = 88
extend_ignore = "E203, E501"

[tool.pytest.ini_options]
asyncio_mode = "strict"

[build-system]
requires = ["setuptools >= 61.2"]
build_backend = "setuptools.build_meta"

[project]
name = "cve-bin-tool"
description = "CVE Binary Checker Tool"
readme = "README.md"
authors = [{ name = "Terri Oda", email = "terri.oda@intel.com" }]
maintainer = [{ name = "Terri Oda", email = "terri.oda@intel.com" }]
license = { text = "GPL-3.0-or-later" }
keywords = ["CVE", "tools", "security"]
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

dynamic = ["dependencies"]

[project.entry_points.scripts]
cve-bin-tool = "cve_bin_tool.cli:main"
csv2cve = "cve_bin_tool.csv2cve:main"

[project.url]
homepage = "https://github.com/intel/cve-bin-tool"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.dependencies]
python = ">=3.7"

[tool.setuptools.dev-dependencies]
reportlab = "*"

[tool.setuptools.extras]
PDF = [
    "reportlab"
]

[tool.setuptools.source]
include = [
    "cve_bin_tool/output_engine/html_reports/templates/*.html",
    "cve_bin_tool/output_engine/html_reports/css/*.css",
    "cve_bin_tool/output_engine/html_reports/js/*.js",
    "cve_bin_tool/output_engine/print_mode/templates/*.html",
    "cve_bin_tool/schemas/*.xsd",
]